### PR TITLE
update the README

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 328ced3 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 328ced3 with merge 328ced3...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/photon/builds/141504408)

**Pull request merged**
