### PR TITLE
use the particle-hal crate

### PR DESCRIPTION
**Pull request by japaric**
TODO
- [ ] update  the README

### CODE REVIEW

**Comment by japaric** [comment]
@dynomu: r+

**Comment by japaric** [comment]
@dynomu: r+

**Comment by dynomu** [comment]
:pushpin: Commit 91f0ba6 has been approved by `japaric`

**Comment by japaric** [comment]
@dynomu: r-

**Comment by japaric** [comment]
@dynomu: r+

**Comment by dynomu** [comment]
:pushpin: Commit 91f0ba6 has been approved by `japaric`

**Comment by japaric** [comment]
@dynomu: r-

**Comment by japaric** [comment]
@dynomu: r+

**Comment by dynomu** [comment]
:pushpin: Commit 91f0ba6 has been approved by `japaric`

**Comment by dynomu** [comment]
:hourglass: Testing commit 91f0ba6 with merge 99deb3e...

**Comment by dynomu** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/photon/builds/126134481)

**Pull request merged**
