### PR TITLE
tweak API for memory safe data sharing between different contexts

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 25fd812 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 25fd812 with merge 25fd812...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/photon/builds/233055762?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 25fd8120b7555cc812500e5e2e9022b7ef6212fb to master...

**Pull request merged**
