### PR TITLE
add CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 505aab2 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 505aab2 with merge 505aab2...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f4fffb1 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f4fffb1 with merge f4fffb1...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit fde951e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit fde951e with merge fde951e...

**Comment by japaric** [comment]
Tests green. Merging.

**Pull request merged**
