### PR TITLE
ci: use newer docker image

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@dynomu: r+

**Comment by dynomu** [comment]
:pushpin: Commit 3a666f0 has been approved by `japaric`

**Comment by dynomu** [comment]
:hourglass: Testing commit 3a666f0 with merge 5a32cd1...

**Comment by dynomu** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/photon/builds/126140402)

**Pull request merged**
